### PR TITLE
ODM-10837: Remove install command from genestack_application_manager

### PR DESCRIPTION
**Pull request by nzorkic-genestack**

### CODE REVIEW

**Review by viapivov — DISMISSED** [review]

**Review by m-smazhevsky — CHANGES_REQUESTED** [review]
I think `genestack_application_manager.py` could be completely removed

**Review by m-smazhevsky — DISMISSED** [review]

**Comment by genestack-okunitsyn** [comment]
Shall we remove [genestack-uploader](https://github.com/genestack/python-client/blob/0eff6de493624f357a47c3f3ab0dc29f4ac1c42e/setup.py#L34) entrypoint  too?

As I can see target script doesn't exist.

**Comment by m-smazhevsky** [comment]
> Shall we remove [genestack-uploader](https://github.com/genestack/python-client/blob/0eff6de493624f357a47c3f3ab0dc29f4ac1c42e/setup.py#L34) entrypoint too?
> 
> As I can see target script doesn't exist.

nice catch! Was removed here: https://github.com/genestack/python-client/commit/45b3178af5e249e5524abd63a6cda7877f347f53

**Review by m-smazhevsky — CHANGES_REQUESTED** [review]
why genestack_application_manager.py is empty but not deleted? Also `genestack-uploader` still here

**Review by m-smazhevsky — APPROVED** [review]

**Pull request merged**
