### PR TITLE
Bump `requests` to v2.31.0

### PR DESCRIPTION
**Pull request by ghost**
Resolving [reported vulnerability](https://github.com/genestack/python-client/security/dependabot/1)

### CODE REVIEW

**Comment by ghost** [comment]
@genestack-okunitsyn, could you please fix up whatever required to make the tests pass?

**Comment by genestack-okunitsyn** [comment]
Yep, sure.

Should works. [Additional PR](https://github.com/genestack/init-image/pull/20/files)

**Comment by ghost** [comment]
@genestack-okunitsyn 
The tests are fine, I'm waiting for your approval and the merge of your PR in _init-image_

**Review by genestack-okunitsyn — APPROVED** [review]

**Comment by genestack-okunitsyn** [comment]
We can merge PR's like this only in the same time to keep autotests in `green` state.

I did it.

**Pull request merged**
